precision mediump float;

varying vec2 fragTexCoord;
uniform sampler2D sampler;

uniform vec2 u; // texture coordinates
uniform vec2 v;


void main()
{
  vec2 uv = vec2(mix(u.x, u.y, fragTexCoord.x), mix(v.x, v.y, fragTexCoord.y)); // this line generated by copilot
  vec4 texelColor = texture2D(sampler, uv);
  if (texelColor.a < 0.1){ // discard png transparent background
    discard;
  }
  else{
    gl_FragColor = texelColor;
  }
}